### PR TITLE
Feature/extended kalibr

### PR DESCRIPTION
**Pull request by rehderj**
@schneith do you think it would be ok to merge this branch?

### CODE REVIEW

**Comment by HannesSommer** [comment]
Hm, this will be cumbersome to merge with the recent developments in aslam_backend_expression in https://github.com/ethz-asl/aslam_optimizer/. 

What are the plans concerning this tragic split?

**Comment by rehderj** [comment]
While I agree with all points raised in our discussion, I would nonetheless like to merge the current state into the master. @HannesSommer, @schneith agreed?

**Comment by HannesSommer** [comment]
Agreed :).

**Comment by schneith** [comment]
Sounds good

**Pull request merged**
