### PR TITLE
Fixed - RS calibration logic

### PR DESCRIPTION
**Pull request by goldbattle**
Hello, and thanks again for continually maintaining this project. Recently we have been trying to calibration a rolling shutter camera and have worked on getting the Kalibr implementation working. There are a few issues with the provided scripts which I have addressed in this PR.

- Removed old opencv import
- Fixed out of date log statement causing crash
- Changed execution permission (so it shows up in rosrun now)
- Fixed design problem creation

The main issue is that the original problem (to my understanding, I could be interpreting the code wrong) assumed that the calibration target was in *full* view during every frame of the dataset. The main problem is that the original implementation does not leverage the feature IDs, so if one frame does not observe a feature, the entire feature array will be "offset" and thus error terms will be in respect to the wrong keypoints. Is this correct? (cc @othlu).

I have addressed this by using a simple dictionary that is used to lookup the correct landmark expression using the IDs. The program runs for our rolling shutter and gives reasonably small values (but non-zero) for our camera. As we don't have any groundtruth to compare against I can vouch if this actually is correctly solving the optimization problem. I can't make a pull request to the wiki, but I think some details on the rolling shutter calibration would help (see #135 #102 #134 #74). Here are the steps that we used to do the rolling shutter calibration:

1. Start with the entire target in view (we used the default [Aprilgrid 6x6 0.8x0.8m](https://github.com/ethz-asl/kalibr/wiki/downloads#calibration-targets))
2. Use a high framerate with low exposure time (we used 30hz with as low of an exposure as possible)
3. Keeping the camera still, we moved the calibration grid very quickly in front of the camera making sure to "skew" the board so that intrinsics are able to calibrate.
4. We just ran the script with the default values as follows:
```
rosrun kalibr kalibr_calibrate_rs_cameras \
--model pinhole-equi-rs --target april_6x6_80x80cm.yaml \
--topic /camera/left --bag dataset_rs.bag \
--inverse-feature-variance 1 --frame-rate 30 
```
5. The script should run and will also do a knot refinement that takes a pretty long time

### CODE REVIEW

**Comment by Zartris** [comment]
It seems I don't have the kalibr_calibration_rs_cameras
Did you do anything specific to get this?

**Comment by goldbattle** [comment]
If you are using the master branch, you should make sure that the main file has the correct execution permissions. On this branch I have [fixed](https://github.com/ethz-asl/kalibr/pull/261/commits/fff120c2b18db4ae8cd1a72c651906375fd902ba#diff-37939fff95d750be5e8d14441ff77d4e) that:
`kalibr_calibrate_rs_cameras 100644 → 100755`

**Comment by mysunnyday** [comment]
hi , thank you for your great work .
as you mentioned in 3, do I have to move the grid rather than move the camera, I use April 0.8m*0.8m , I think move the camera may be easier. 
then I know the kalibr_calibrate_rs_cameras only calibrate the camera , is there any command for cam-imu calib with rolling shutter camera ?

**Comment by goldbattle** [comment]
You can move either the camera or the target board since you are not calibrating the IMU.

I just used the normal cam-imu calibration script since writing a cam-imu for rs is a large task that I didn't have time for. The focal lengths seemed to be of close values (i used smooth slow motion during capturing).

**Comment by mysunnyday** [comment]
ok thank you for your reply so quickly. 
I'm trying to calib the imu's scale-misalignment and init bias with extend method, so I'm worrying that the rolling shutter may spoil this process.

**Comment by mysunnyday** [comment]
hi I have got the result with your commit , but unlike normal kalibr_calibrate_camera , kalibr_calibrate_rs_camera didn't provide reproj error and any report, I only got the result in each running like :
> LineDelay:
> 6.42300540615e-05
> Intrinsics:
> [ 490.9528265   491.02249874  311.3157732   237.93255763]
> Distortion:
> [ 0.06609487 -0.12530943  0.00038954  0.00005515]
so is there any evaluation target to verify my result ?

**Comment by goldbattle** [comment]
As of right now, no, but if you have another system that is able to estimate this value, you could use that to compare to this. You might be able to look at the other scripts to see if you can pull out a reprojection errror also.

**Comment by liwei-x** [comment]
hi, i also got the result  by using your commit. But when i use the camera intrinsics and distortion parameters for camera pose estimation, the camera trajectory is an ellipse in rotation. 
I don't know what's wrong with my results?

LineDelay:
8.71653641451e-05
Intrinsics:
[ 261.9098677   261.03554036  314.15039534  171.28585777]
Distortion:
[ 0.43250912  0.04113028 -0.28348954  0.07630278]

**Comment by vhanded** [comment]
I tried your method of moving grid fast, and obtain the following result:

```
[ WARN] [1561557669.742955]: landmark 176 in frame 568 not in first frame
[ WARN] [1561557669.745303]: landmark 177 in frame 568 not in first frame
[ WARN] [1561557669.748237]: landmark 190 in frame 568 not in first frame
.....
.....
.....
[ WARN] [1561557669.788257]: landmark 176 in frame 571 not in first frame
[ WARN] [1561557669.791009]: landmark 177 in frame 571 not in first frame
[ WARN] [1561557669.793899]: landmark 190 in frame 571 not in first frame
[ WARN] [1561557669.796162]: landmark 191 in frame 571 not in first frame
run new optimisation with initial values:

LineDelay:
6.94444444444e-05
Intrinsics:
[   0.     0.   319.5  239.5]
Distortion:
[ 0.  0.  0.  0.]
Using the block_cholesky linear system solver
Using the dog_leg trust region policy
Using the block_cholesky linear system solver
Using the dog_leg trust region policy
Initializing
Optimization problem initialized with 216 design variables and 129196 error terms
The Jacobian matrix is 258391 x 1287
[0.0]: J: -nan
Exception in thread block: Time is out of dual 32-bit range
Exception in thread block: Time is out of dual 32-bit range
Exception in thread block: Time is out of dual 32-bit range
Exception in thread block: Time is out of dual 32-bit range
[ERROR] [1561557673.171523]: Exception: std::exception
```
What do LineDelay mean in this context?

My end goal is to calibrate multiple cameras, to obtain their pose. In the reply above, it returned LineDelay, Intrinsics, Distortion. What this data can do?

Thanks, and excuse me if the answer is obvious.

**Comment by goldbattle** [comment]
It looks like it was unable to find the initial guess of the focal length, thus the NaN and optimization failure.
This likely means that extraction failed? or the board parameters are wrong?
My best guesses.

The line delay is the number of seconds it takes to read a single line from the camera sensor. So if you want the whole image delay you would do LineDelay*ImgHeight is how long the sensor takes to read out. I would read section 3.2 in this [paper](https://www.cv-foundation.org/openaccess/content_cvpr_2013/papers/Oth_Rolling_Shutter_Camera_2013_CVPR_paper.pdf).

This script is only for single camera, so I would recommend you take a look at the wiki for the multi-cam script (which doesn't have rolling shutter support).

**Comment by vhanded** [comment]
So I recapture the grid, this time try to show as much grid as possible in every frame, and there is no `std:exception` error. I successfully obtain the below value.

```
LineDelay:
3.21144037146e-05
Intrinsics:
[ 671.89684306  673.43573204  309.03709118  231.25379074]
Distortion:
[ 0.02550479 -0.04081717 -0.0005938   0.00175584]

```

The question is same as previous, my aim is to calibrate multiple cameras, to obtain their pose. what do LineDelay, Intrinsics, Distortion can do?

Thanks.

**Comment by goldbattle** [comment]
This is a calibration toolbox, you would need to use some other software to do your state estimation. Just search "structure from motion" or "simultaneous localization and mapping" and that should get you started.

If you want to do multi-cam you could try using the non-rolling shutter code and move your target board very slow to minimize the rolling shutter effect (the cameras do need to have overlapping views).

**Comment by helenol** [comment]
add to whitelist

**Comment by hitimo** [comment]
test this please

**Comment by hitimo** [comment]
test this please

**Comment by JzHuai0108** [comment]
This is a great pull request. To my understanding, it indeed relaxes the assumption "that the calibration target was in full view during every frame of the dataset". However, in the pull request, only landmarks showing up in the first image of the target are used in optimization, see line 339-346 in the pull request. Preferably, all landmarks of the target should be used. 
So has been done in [my commit on the forked Kalibr](https://github.com/JzHuai0108/kalibr/commit/603be610adc960d99d04e2bd10fd5769fde2ee9a).

**Comment by hitimo** [comment]
Thanks for the PR @goldbattle 

More fixes for RS calibration will follow in new PR.

**Pull request merged**
