### PR TITLE
European Union instead of Community

### PR DESCRIPTION
**Pull request by HannesSommer**
[skip ci]

### CODE REVIEW

**Comment by schneith** [comment]
I have a 3rd suggestion :) Here https://ec.europa.eu/research/fp7/index_en.cfm EC stands for European Comission.

**Comment by HannesSommer** [comment]
Yes, I guess commission is already closer than community :). BUT the mode of acknowledge phrase examples seems to be at "... EU's ...".

**Comment by schneith** [comment]
Sounds good.

**Comment by schneith** [comment]
That is really confusing what we should use. Here they also use community: http://europa2.informatik.uni-freiburg.de/ , and also in this paper: https://www.inf.ethz.ch/personal/pomarc/pubs/HengIROS13.pdf

**Comment by HannesSommer** [comment]
I think the problem is that the EC existed 1993-2009 (https://en.wikipedia.org/wiki/European_Economic_Community). So, it might have been correct till some time! But as it doesn't exist since then it can't be correct anymore.

I'd assume since then it is just a little bug that grew and grew thanks to the copy and paste habit.

**Comment by HannesSommer** [comment]
According to Britannica : "With the treaty’s entry into force on Dec. 1, 2009, the name **European Community** as well as the “pillars” concept were **eliminated**." ^^

(https://www.britannica.com/topic/European-Community-European-economic-association)

**Comment by schneith** [comment]
The Seventh Framework Programme was from 2007-2013. Hm, so it could actually still be European Community?

**Comment by HannesSommer** [comment]
But as far as I know both V-Charge and EUROPA2 both start after 2009. Therefore they were never supported by the EC but by they EU (which was even true at the time when the EC still existed, because it was always a part of the EU).

**Comment by schneith** [comment]
Oke, makes sense.

**Pull request merged**
