### PR TITLE
Enable temporal calibration by default.

### PR DESCRIPTION
**Pull request by schneith**

### CODE REVIEW

**Comment by schneith** [comment]
@schneith update wiki before merge

**Comment by ZacharyTaylor** [comment]
If the temporal calibration defaults are being changed could we also change --timeoffset-paddings default as the offset is almost always greater than the default max of 10ms

**Comment by schneith** [comment]
Sounds good to me. Do you have a guess what value could make sense? 100ms? Would that still be fast enough?

**Comment by ZacharyTaylor** [comment]
I think just bringing it up to 20 or 30ms would solve 90% of cases

**Pull request merged**
