### PR TITLE
Add support for float numpy>=1.24

### PR DESCRIPTION
**Pull request by jaku-jaku**
+ numpy float deprecated

### CODE REVIEW

**Comment by goldbattle** [comment]
Does this have backwards compatibility? What version of OS / libs are you using?

**Comment by jaku-jaku** [comment]
> Does this have backwards compatibility? What version of OS / libs are you using?
OS: Ubuntu 20.04 | ROS Noetic | Python 3.8.10 | numpy: 1.24.1
```python
import numpy as np
np.float
```
Output: 
```
AttributeError: module 'numpy' has no attribute 'float'
```

As stated in [numpy 1.20 - deprecations](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations), it will be no longer supported due to duplication.
Hence, I believe it is not backward compatible from numpy 1.20

**Comment by adthoms** [comment]
@goldbattle are there plans to merge this PR?

**Comment by goldbattle** [comment]
I have not had time to reproduce in a docker container and ensure it has backwards compatibility. Need to also verify that this is the only place that needs it, and likely create a ubuntu 22 docker.

**Comment by jaku-jaku** [comment]
As refer from https://stackoverflow.com/questions/74844262/how-can-i-solve-error-module-numpy-has-no-attribute-float-in-python
> NumPy 1.20 [(release notes)](https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations) deprecated numpy.float, numpy.int, and similar aliases, causing them to issue a deprecation warning
> NumPy 1.24 [(release notes)](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) removed these aliases altogether, causing an error when they are used

I will make a test locally and update this PR with backward support

**Comment by jaku-jaku** [comment]
Fixes tested:
```bash
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.float
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jx/.local/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
>>> numpy.float64
<class 'numpy.float64'>
>>> numpy.version.version
'1.24.0'
```
and backward `$ pip3 install numpy==1.17.4`
```bash
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.float
<class 'float'>
>>> numpy.float64
<class 'numpy.float64'>
>>> numpy.version.version
'1.17.4'
```

**Comment by jaku-jaku** [comment]
@adthoms @goldbattle Done, and tested for backward and forward compatible.

You can replicate the above issue on the main branch by `pip install numpy==1.24`, and you will see the error.
You can remove the issue by setting `pip install numpy==1.23` or specify `np.float64` (with this latest fix)

**Comment by goldbattle** [comment]
Many thanks for the detailed PR and steps to test, was able to reproduce and this PR fixed the issues. Many thanks.

**Pull request merged**
