### PR TITLE
@burrimi : could you tell me if this is the proper way to do it?

### PR DESCRIPTION
**Pull request by nikolicj**

### CODE REVIEW

**Comment by omaris** [comment]
You can draw inspiration from https://github.com/ethz-asl/kalibr/pull/8

I use this PR as basis to run Kalibr in Indigo.

**Comment by nikolicj** [comment]
Thanks, great. I assume it's unsafe to merge #8 into master, for ros hydro compatibility?

**Comment by omaris** [comment]
That is a good question. Does someone have Hydro running? To check this,
one would need an Ubuntu 12.04 or 13.X...

**Comment by NikolausDemmel** [comment]
Changes look good to me and make sense +1.

I do something similar to compile on indigo. Haven't tried on hydro though.

Obviously for indigo the `imgmsg_to_cv2` change is needed as well, as in #8.

@omaris: It is pretty simple to compile hydro from source on 14.04 if you want it for testing: http://wiki.ros.org/hydro/Installation/OSX/Homebrew/Source

**Comment by schneith** [comment]
test this please

**Comment by schneith** [comment]
ok to test

**Comment by goldbattle** [comment]
Closing due to age.

**Pull request closed without merging**
