### PR TITLE
CMake finds correct Eigen config in Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by pkok**
The installation tutorial instructs to install Eigen3.  A standard
Ubuntu installation has no FindEigen.cmake, but only FindEigen3.cmake.
Therefore, I instructed CMake to require Eigen3 instead of Eigen.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
using `cmake_modules

**Comment by schneith** [comment]
test this please

**Comment by schneith** [comment]
test this please

**Comment by schneith** [comment]
test this please

**Pull request closed without merging**
